### PR TITLE
Simplified the test in highlightKeywords function

### PR DESCRIPTION
**Pull request by fialhorenato**
We can use `content?` instead of `if content isnt null and content isnt undefined`

### CODE REVIEW

**Comment by hugodias** [comment]
Inside the function the "content?" will produce a " ! =" comparison when compiled to javascript. We need a "! ==" comparison .

Here you can see the difference

Imgur

**Comment by fialhorenato** [comment]
WTF?

Why this difference?

[image: Imagem inline 1]

*__________________________________________*


*Renato da Silva Reis Fialho*Computer Science Student
*Mobile*  | +55 (31) 9476-6281
*VoIP*  | +1 (312) 857-4689
renato@renatofialho.com

2015-10-16 15:24 GMT-03:00 Hugo Dias <notifications@github.com>:

**Comment by fialhorenato** [comment]
WTF?

Why?

captura de tela 2015-10-16 as 16 05 09

**Comment by fialhorenato** [comment]
Pull it! :+1: 

http://stackoverflow.com/questions/19294924/coffee-existential-operator-different-compliations

So, basically

`content != null` already checks for null or undefined, and `content !== null` checks only for null :+1:

**Comment by hugodias** [comment]
[Why we should always compare using !== in Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#A_model_for_understanding_equality_comparisons)

**Comment by fialhorenato** [comment]
Makes sense, but on this question we're trying to know if they exists, so it works :imp:

**Pull request closed without merging**
